### ISSUE TITLE
狀態欄有點突兀

### ISSUE THREAD

**Issue by Rnagerwww** [bluebonnet27/SunRain#1]
![Screenshot_20210103-125539](https://user-images.githubusercontent.com/74822076/103472037-33ec0780-4dc3-11eb-9e13-0d2fd29b4780.png)
上面狀態欄好像看起來不是很沉浸啊😯

**Comment by bluebonnet27** [comment]
> 
> 
> ![Screenshot_20210103-125539](https://user-images.githubusercontent.com/74822076/103472037-33ec0780-4dc3-11eb-9e13-0d2fd29b4780.png)
> 上面狀態欄好像看起來不是很沉浸啊😯

谢谢，但是没有找到什么好的解决方案，这个问题在我的 mi 8 上没有出现，但在测试用的 pixel 上出现了。
