### ISSUE TITLE
正式日期下「今天」显示为「昨天」的日期

### ISSUE THREAD

**Issue by ghost** [bluebonnet27/SunRain#3]
今天是 5 月 14 日，经彩云天气 app 确认 8-17 °C 是 5 月 14 日的温度。
![Screenshot_20210514-153907](https://user-images.githubusercontent.com/82031146/118252455-9cae6380-b4ca-11eb-9c60-5e7b7b277aa7.png)

**Comment by bluebonnet27** [comment]
你好：



谢谢你发现的bug，正在查找相关原因，顺利的话预计会在下个稳定版本修复。


感谢您对此项目的关心。



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bluebonnet27/SunRain"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月14日(星期五) 下午5:41
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[bluebonnet27/SunRain] 正式日期下「今天」显示为「昨天」的日期 (#3)





 
今天是 5 月 14 日，经彩云天气 app 确认 8-17 °C 是 5 月 14 日的温度。
